FactoryGirl.define do
  factory :legislator do
    title "MyString"
firstname "MyString"
middlename "MyString"
lastname "MyString"
name_suffix "MyString"
nickname "MyString"
party "MyString"
state "MyString"
district "MyString"
in_office "MyString"
gender "MyString"
phone "MyString"
fax "MyString"
website "MyString"
webform "MyString"
congress_office "MyString"
bioguide_id "MyString"
votesmart_id "MyString"
fec_id "MyString"
govtrack_id "MyString"
crp_id "MyString"
twitter_id "MyString"
congresspedia_url "MyString"
youtube_url "MyString"
facebook_id "MyString"
official_rss "MyString"
senate_class "MyString"
birthdate "MyString"
oc_email "MyString"
  end

end
