development:
  secret_key_base: <%= ENV["GOOD_DEEDS_DEV_SECRET_KEY"] %>

test:
  secret_key_base: <%= ENV["GOOD_DEEDS_TEST_SECRET_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
